#!/usr/bin/php
<?
set_include_path("../include");
require("header.inc.php");

require("../model/Error.inc.php");

if (empty($argv[1]) || empty($argv[2]) {
	die("Usage: $argv[0] " . 'groupname username' . "\n");
}

$groupname = $argv[1];
$username = $argv[2];

$userID = Zotero_Users::getUserIDFromUsername($username);
if (!$userID) {
  die("User '$user' unknown\n");
}

$sql = "SELECT groupID FROM groups WHERE name=?";
$groupID = Zotero_DB::valueQuery($sql, array($groupname));
if ($groupID === false) {
  die("Group '$groupname' unknown.\n");
}

$group = Zotero_Groups::get($groupID);

try {
  
    $group->removeUser($userID);
    $msg = "User '$userID' removed from group '$groupID'.\n";
  }

  $group->save();
} catch (Exception $e) {
  die($e->getMessage()."\n");
}

echo $msg;

?>